
unused = "Color00"

[default]
  black = "Color00"
  gray1 = "Color08"
  gray2 = "Color08"
  gray3 = "Color08"
  gray4 = "Color08"
  white = "Color0f"
  red = "Color09"
  yellow = "Color0b"
  green = "Color0a"
  cyan  = "Color0e"
  blue = "Color04"
  purple = "Color05"

[dark]
  button = ["default.black","default.gray1"]
  button-focus = ["default.white","default.purple"]
  button-selected = ["default.white","default.black"]
  cmdline = ["default.black","default.yellow"]
  cmdline-button = ["default.yellow","default.black"]
  cmdline-border = ["default.black","default.yellow"]
  copy-mode = ["default.black","default.yellow"]
  copy-mode-alt = ["default.yellow","default.black"]
  copy-mode-label = ["default.white","default.red"]
  current-capture = ["default.white","themes.unused"]
  dialog = ["default.black","default.yellow"]
  dialog-button = ["default.yellow","default.black"]
  default = ["default.white","default.black"]
  filter-empty = ["default.black","default.cyan"]
  filter-intermediate = ["default.black","default.yellow"]
  filter-invalid = ["default.black","default.red"]
  filter-menu = ["default.white","default.black"]
  filter-valid = ["default.black","default.green"]
  hex-byte-selected = ["default.black","default.purple"]
  hex-byte-unselected = ["default.white","default.black"]
  hex-field-selected = ["default.black","default.cyan"]
  hex-field-unselected = ["default.black","default.white"]
  hex-interval-selected = ["default.white","default.gray2"]
  hex-interval-unselected = ["default.white","default.gray1"]
  hex-layer-selected = ["default.white","default.gray2"]
  hex-layer-unselected = ["default.white","default.gray1"]
  packet-list-cell-focus = ["default.black","default.purple"]
  packet-list-cell-selected = ["default.white","default.gray2"]
  packet-list-row-focus = ["default.gray2","default.cyan"]
  packet-list-row-selected = ["default.white","default.gray1"]
  packet-struct-focus = ["default.black","default.cyan"]
  packet-struct-selected = ["default.black","default.gray2"]
  progress-complete = ["default.white","default.purple"]
  progress-default = ["default.white","default.black"]
  progress-spinner = ["default.yellow","default.purple"]
  spinner = ["default.yellow","default.black"]
  stream-client = ["default.black","default.red"]
  stream-match = ["default.black","default.yellow"]
  stream-search = ["default.black","default.white"]
  stream-server = ["default.cyan","default.blue"]
  title = ["default.red","unused"]

[light]
  button = ["default.white","default.gray3"]
  button-focus = ["default.white","default.purple"]
  button-selected = ["default.black","default.gray3"]
  cmdline = ["default.black","default.yellow"]
  cmdline-button = ["default.yellow","default.black"]
  cmdline-border = ["default.black","default.yellow"]
  copy-mode = ["default.white","default.yellow"]
  copy-mode-alt = ["default.yellow","default.white"]
  copy-mode-label = ["default.black","default.red"]
  current-capture = ["default.black","unused"]
  dialog = ["default.black","default.yellow"]
  dialog-button = ["default.yellow","default.black"]
  default = ["default.black","default.white"]
  filter-empty = ["default.black","default.cyan"]
  filter-intermediate = ["default.black","default.yellow"]
  filter-invalid = ["default.black","default.red"]
  filter-menu = ["default.black","default.white"]
  filter-valid = ["default.black","default.green"]
  hex-byte-selected = ["default.black","default.purple"]
  hex-byte-unselected = ["default.black","default.white"]
  hex-field-selected = ["default.black","default.cyan"]
  hex-field-unselected = ["default.black","default.gray2"]
  hex-interval-selected = ["default.white","default.gray2"]
  hex-interval-unselected = ["default.black","default.gray4"]
  hex-layer-selected = ["default.white","default.gray2"]
  hex-layer-unselected = ["default.black","default.gray4"]
  packet-list-cell-focus = ["default.black","default.purple"]
  packet-list-cell-selected = ["default.black","default.gray3"]
  packet-list-row-focus = ["default.black","default.cyan"]
  packet-list-row-selected = ["default.black","default.gray4"]
  packet-struct-focus = ["default.black","default.cyan"]
  packet-struct-selected = ["default.black","default.gray4"]
  progress-complete = ["default.white","default.purple"]
  progress-default = ["default.white","default.black"]
  progress-spinner = ["default.yellow","default.black"]
  spinner = ["default.yellow","default.white"]
  stream-client = ["default.white","default.red"]
  stream-match = ["default.white","default.yellow"]
  stream-search = ["default.white","default.black"]
  stream-server = ["default.cyan","default.blue"]
  title = ["default.red","unused"]
