
unused = "#79e11a"

[dracula]
  gray1 = "#464752"
  gray2 = "#565761"
  gray3 = "#b6b6b2"
  gray4 = "#ccccc7"
  black = "#282a36"
  blue = "#6272a4"
  cyan = "#8be9fd"
  green = "#50fa7b"
  magenta = "#ff79c6"
  orange = "#ffb86c"
  purple = "#bd93f9"
  red = "#ff5555"
  white = "#f8f8f2"
  yellow = "#f1fa8c"

[dark]
  button = ["dracula.black","dracula.gray3"]
  button-focus = ["dracula.black","dracula.magenta"]
  button-selected = ["dracula.white","dracula.gray3"]
  cmdline = ["dracula.black","dracula.yellow"]
  cmdline-button = ["dracula.yellow","dracula.black"]
  cmdline-border = ["dracula.black","dracula.yellow"]
  copy-mode = ["dracula.black","dracula.yellow"]
  copy-mode-alt = ["dracula.yellow","dracula.black"]
  copy-mode-label = ["dracula.white","dracula.red"]
  current-capture = ["dracula.white","themes.unused"]
  dialog = ["dracula.black","dracula.yellow"]
  dialog-button = ["dracula.yellow","dracula.black"]
  default = ["dracula.white","dracula.black"]
  filter-empty = ["dracula.black","dracula.cyan"]
  filter-intermediate = ["dracula.black","dracula.orange"]
  filter-invalid = ["dracula.black","dracula.red"]
  filter-menu = ["dracula.white","dracula.black"]
  filter-valid = ["dracula.black","dracula.green"]
  hex-byte-selected = ["dracula.white","dracula.purple"]
  hex-byte-unselected = ["dracula.white","dracula.black"]
  hex-field-selected = ["dracula.black","dracula.cyan"]
  hex-field-unselected = ["dracula.black","dracula.white"]
  hex-interval-selected = ["dracula.white","dracula.gray2"]
  hex-interval-unselected = ["dracula.white","dracula.gray1"]
  hex-layer-selected = ["dracula.white","dracula.gray2"]
  hex-layer-unselected = ["dracula.white","dracula.gray1"]
  packet-list-cell-focus = ["dracula.white","dracula.purple"]
  packet-list-cell-selected = ["dracula.white","dracula.gray2"]
  packet-list-row-focus = ["dracula.white","dracula.cyan"]
  packet-list-row-selected = ["dracula.white","dracula.gray1"]
  packet-struct-focus = ["dracula.black","dracula.cyan"]
  packet-struct-selected = ["dracula.black","dracula.gray2"]
  progress-complete = ["dracula.white","dracula.purple"]
  progress-default = ["dracula.white","dracula.black"]
  progress-spinner = ["dracula.yellow","dracula.purple"]
  spinner = ["dracula.yellow","dracula.black"]
  stream-client = ["dracula.black","dracula.red"]
  stream-match = ["dracula.black","dracula.yellow"]
  stream-search = ["dracula.black","dracula.white"]
  stream-server = ["dracula.white","dracula.blue"]
  title = ["dracula.red","unused"]

[light]
  button = ["dracula.black","dracula.white"]
  button-focus = ["dracula.black","dracula.purple"]
  button-selected = ["dracula.black","dracula.gray3"]
  cmdline = ["dracula.black","dracula.yellow"]
  cmdline-button = ["dracula.yellow","dracula.black"]
  cmdline-border = ["dracula.black","dracula.yellow"]
  copy-mode = ["dracula.white","dracula.yellow"]
  copy-mode-alt = ["dracula.yellow","dracula.white"]
  copy-mode-label = ["dracula.black","dracula.red"]
  current-capture = ["dracula.black","unused"]
  dialog = ["dracula.black","dracula.yellow"]
  dialog-button = ["dracula.yellow","dracula.black"]
  default = ["dracula.black","dracula.white"]
  filter-empty = ["dracula.black","dracula.cyan"]
  filter-intermediate = ["dracula.black","dracula.orange"]
  filter-invalid = ["dracula.black","dracula.red"]
  filter-menu = ["dracula.black","dracula.white"]
  filter-valid = ["dracula.black","dracula.green"]
  hex-byte-selected = ["dracula.white","dracula.purple"]
  hex-byte-unselected = ["dracula.black","dracula.white"]
  hex-field-selected = ["dracula.black","dracula.cyan"]
  hex-field-unselected = ["dracula.black","dracula.gray2"]
  hex-interval-selected = ["dracula.white","dracula.gray2"]
  hex-interval-unselected = ["dracula.black","dracula.gray4"]
  hex-layer-selected = ["dracula.white","dracula.gray2"]
  hex-layer-unselected = ["dracula.black","dracula.gray4"]
  packet-list-cell-focus = ["dracula.white","dracula.purple"]
  packet-list-cell-selected = ["dracula.black","dracula.gray3"]
  packet-list-row-focus = ["dracula.white","dracula.cyan"]
  packet-list-row-selected = ["dracula.black","dracula.gray4"]
  packet-struct-focus = ["dracula.black","dracula.cyan"]
  packet-struct-selected = ["dracula.black","dracula.gray4"]
  progress-complete = ["dracula.white","dracula.purple"]
  progress-default = ["dracula.white","dracula.black"]
  progress-spinner = ["dracula.yellow","dracula.black"]
  spinner = ["dracula.yellow","dracula.white"]
  stream-client = ["dracula.white","dracula.red"]
  stream-match = ["dracula.white","dracula.yellow"]
  stream-search = ["dracula.white","dracula.black"]
  stream-server = ["dracula.white","dracula.blue"]
  title = ["dracula.red","unused"]
