
unused = "#79e11a"

[solarized]
  gray1 = "#586e75"
  gray2 = "#657b83"
  gray3 = "#839496"
  gray4 = "#93a1a1"
  black = "#002b36"
  blue = "#268bd2"
  cyan = "#2aa198"
  green = "#859900"
  magenta = "#d33682"
  orange = "#cb4b16"
  purple = "#6c71c4"
  red = "#dc322f"
  white = "#fdf6e3"
  yellow = "#B58900"

[dark]
  button = ["solarized.black","solarized.gray3"]
  button-focus = ["solarized.white","solarized.magenta"]
  button-selected = ["solarized.white","solarized.gray3"]
  cmdline = ["solarized.black","solarized.yellow"]
  cmdline-button = ["solarized.yellow","solarized.black"]
  cmdline-border = ["solarized.black","solarized.yellow"]
  copy-mode = ["solarized.black","solarized.yellow"]
  copy-mode-alt = ["solarized.yellow","solarized.black"]
  copy-mode-label = ["solarized.white","solarized.red"]
  current-capture = ["solarized.white","unused"]
  dialog = ["solarized.black","solarized.yellow"]
  dialog-button = ["solarized.yellow","solarized.black"]
  default = ["solarized.white","solarized.black"]
  filter-empty = ["solarized.black","solarized.cyan"]
  filter-intermediate = ["solarized.black","solarized.orange"]
  filter-invalid = ["solarized.black","solarized.red"]
  filter-menu = ["solarized.white","solarized.black"]
  filter-valid = ["solarized.black","solarized.green"]
  hex-byte-selected = ["solarized.white","solarized.purple"]
  hex-byte-unselected = ["solarized.white","solarized.black"]
  hex-field-selected = ["solarized.black","solarized.cyan"]
  hex-field-unselected = ["solarized.black","solarized.white"]
  hex-interval-selected = ["solarized.white","solarized.gray2"]
  hex-interval-unselected = ["solarized.white","solarized.gray1"]
  hex-layer-selected = ["solarized.white","solarized.gray2"]
  hex-layer-unselected = ["solarized.white","solarized.gray1"]
  packet-list-cell-focus = ["solarized.white","solarized.purple"]
  packet-list-cell-selected = ["solarized.white","solarized.gray2"]
  packet-list-row-focus = ["solarized.white","solarized.cyan"]
  packet-list-row-selected = ["solarized.white","solarized.gray1"]
  packet-struct-focus = ["solarized.black","solarized.cyan"]
  packet-struct-selected = ["solarized.black","solarized.gray2"]
  progress-complete = ["solarized.white","solarized.purple"]
  progress-default = ["solarized.white","solarized.black"]
  progress-spinner = ["solarized.yellow","solarized.purple"]
  spinner = ["solarized.yellow","solarized.black"]
  stream-client = ["solarized.white","solarized.red"]
  stream-match = ["solarized.black","solarized.yellow"]
  stream-search = ["solarized.black","solarized.white"]
  stream-server = ["solarized.white","solarized.blue"]
  title = ["solarized.red","unused"]

[light]
  button = ["solarized.black","solarized.white"]
  button-focus = ["solarized.white","solarized.purple"]
  button-selected = ["solarized.black","solarized.gray3"]
  cmdline = ["solarized.black","solarized.yellow"]
  cmdline-button = ["solarized.yellow","solarized.black"]
  cmdline-border = ["solarized.black","solarized.yellow"]
  copy-mode = ["solarized.white","solarized.yellow"]
  copy-mode-alt = ["solarized.yellow","solarized.white"]
  copy-mode-label = ["solarized.black","solarized.red"]
  current-capture = ["solarized.black","unused"]
  dialog = ["solarized.black","solarized.yellow"]
  dialog-button = ["solarized.yellow","solarized.black"]
  default = ["solarized.black","solarized.white"]
  filter-empty = ["solarized.black","solarized.cyan"]
  filter-intermediate = ["solarized.black","solarized.orange"]
  filter-invalid = ["solarized.black","solarized.red"]
  filter-menu = ["solarized.black","solarized.white"]
  filter-valid = ["solarized.black","solarized.green"]
  hex-byte-selected = ["solarized.white","solarized.purple"]
  hex-byte-unselected = ["solarized.black","solarized.white"]
  hex-field-selected = ["solarized.black","solarized.cyan"]
  hex-field-unselected = ["solarized.black","solarized.gray2"]
  hex-interval-selected = ["solarized.white","solarized.gray2"]
  hex-interval-unselected = ["solarized.black","solarized.gray4"]
  hex-layer-selected = ["solarized.white","solarized.gray2"]
  hex-layer-unselected = ["solarized.black","solarized.gray4"]
  packet-list-cell-focus = ["solarized.white","solarized.purple"]
  packet-list-cell-selected = ["solarized.black","solarized.gray3"]
  packet-list-row-focus = ["solarized.white","solarized.cyan"]
  packet-list-row-selected = ["solarized.black","solarized.gray4"]
  packet-struct-focus = ["solarized.black","solarized.cyan"]
  packet-struct-selected = ["solarized.black","solarized.gray4"]
  progress-complete = ["solarized.white","solarized.purple"]
  progress-default = ["solarized.white","solarized.black"]
  progress-spinner = ["solarized.yellow","solarized.black"]
  spinner = ["solarized.yellow","solarized.white"]
  stream-client = ["solarized.white","solarized.red"]
  stream-match = ["solarized.white","solarized.yellow"]
  stream-search = ["solarized.white","solarized.black"]
  stream-server = ["solarized.white","solarized.blue"]
  title = ["solarized.red","unused"]

